package main

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/sadirano/onix/internal/plugins"
	"github.com/sadirano/onix/internal/snippet"
)

// snippetPathForOS returns the snippet file the host platform actually
// reads/writes. The tests drive the public extractSnippetPin /
// checkSnippetPin entry points, which now branch on runtime.GOOS, so the
// test setup has to write whichever file those functions will look at.
func snippetPathForOS(home string) string {
	if runtime.GOOS == "windows" {
		return snippet.PwshPath(home)
	}
	return snippet.BashPath(home)
}

// staleSnippetBody returns a snippet body in the host platform's format
// that does NOT contain the pin line, used by the "missing pin" test.
func staleSnippetBody() string {
	if runtime.GOOS == "windows" {
		return "# stale snippet\nfunction global:o { }\n"
	}
	return "# stale snippet\no() { :; }\n"
}

// missingPinBody returns a snippet body in the host platform's format with
// the pin line pointing at a path that definitely does not exist.
func missingPinBody() string {
	if runtime.GOOS == "windows" {
		return "$global:onixExe = 'C:\\nope\\does-not-exist.exe'\n"
	}
	return "export ONIX_EXE='/nope/does-not-exist'\n"
}

// TestExtractSnippetPin covers the parser's three branches: a snippet
// written by writeShellSnippet (the happy path), a snippet missing the
// pin line (hand-edited or generated by an older onix), and a non-existent
// snippet (covered by checkShellSnippet upstream).
func TestExtractSnippetPin(t *testing.T) {
	t.Run("happy path", func(t *testing.T) {
		dir := t.TempDir()
		if err := snippet.WriteShellSnippet(dir, nil, nil, nil); err != nil {
			t.Fatalf("write: %v", err)
		}
		pin := extractSnippetPin(dir)
		if pin == "" {
			t.Fatal("extractSnippetPin returned empty for a freshly-generated snippet")
		}
		// The pin must point at the running test binary, which is what
		// writeShellSnippet embedded via os.Executable().
		exe, err := os.Executable()
		if err != nil {
			t.Fatalf("os.Executable: %v", err)
		}
		if snippet.OnixExeOverride != "" {
			exe = snippet.OnixExeOverride
		}
		if !samePath(pin, exe) {
			t.Errorf("pin = %q, want path equivalent to %q", pin, exe)
		}
	})

	t.Run("missing pin line", func(t *testing.T) {
		dir := t.TempDir()
		// Drop a snippet that does not declare the pin (older shape).
		if err := os.MkdirAll(filepath.Join(dir, "shell"), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(snippetPathForOS(dir), []byte(staleSnippetBody()), 0o644); err != nil {
			t.Fatal(err)
		}
		if pin := extractSnippetPin(dir); pin != "" {
			t.Errorf("pin = %q, want empty for snippet without pin line", pin)
		}
	})

	t.Run("missing snippet", func(t *testing.T) {
		dir := t.TempDir()
		if pin := extractSnippetPin(dir); pin != "" {
			t.Errorf("pin = %q, want empty when snippet file is absent", pin)
		}
	})
}

// TestCheckSnippetPin walks the doctor check itself through its three
// outcomes: ok, warn (no pin), warn (pinned path missing).
func TestCheckSnippetPin(t *testing.T) {
	t.Run("ok when snippet is fresh", func(t *testing.T) {
		dir := t.TempDir()
		if err := snippet.WriteShellSnippet(dir, nil, nil, nil); err != nil {
			t.Fatal(err)
		}
		r := checkSnippetPin(dir)
		want := "ok"
		if snippet.OnixExeOverride != "" {
			if _, err := os.Stat(snippet.OnixExeOverride); err != nil {
				want = "warn"
			}
		}
		if r.Status != want {
			t.Errorf("Status = %q, want %q (Detail=%s)", r.Status, want, r.Detail)
		}
	})

	t.Run("skipped when snippet missing", func(t *testing.T) {
		dir := t.TempDir()
		r := checkSnippetPin(dir)
		if r.Name != "" {
			t.Errorf("expected zero-value result when snippet absent, got %+v", r)
		}
	})

	t.Run("warn when pin points to missing file", func(t *testing.T) {
		dir := t.TempDir()
		if err := os.MkdirAll(filepath.Join(dir, "shell"), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(snippetPathForOS(dir), []byte(missingPinBody()), 0o644); err != nil {
			t.Fatal(err)
		}
		r := checkSnippetPin(dir)
		if r.Status != "warn" {
			t.Errorf("status = %q, want warn (detail=%s)", r.Status, r.Detail)
		}
		if !strings.Contains(r.Detail, "missing") {
			t.Errorf("detail = %q, want it to mention 'missing'", r.Detail)
		}
	})
}

// TestCheckBashLikeProfile exercises the three branches of the Linux
// shell-profile check: no rc files found, rc file present but doesn't
// source the snippet, rc file sources the snippet.
//
// We point USERPROFILE/HOME at a tempdir so the real user's rc files
// never participate. On Windows the function still reads $HOME via
// os.UserHomeDir; the t.Setenv calls cover both variants.
func TestCheckBashLikeProfile(t *testing.T) {
	t.Run("warn when no rc files", func(t *testing.T) {
		home := t.TempDir()
		t.Setenv("HOME", home)
		t.Setenv("USERPROFILE", home)
		r := checkBashLikeProfile(home)
		if r.Status != "warn" {
			t.Errorf("status = %q, want warn (no rc files)", r.Status)
		}
		if !strings.Contains(r.Detail, "neither") {
			t.Errorf("detail = %q, want it to mention missing rc files", r.Detail)
		}
	})

	t.Run("warn when rc files exist but don't source", func(t *testing.T) {
		home := t.TempDir()
		t.Setenv("HOME", home)
		t.Setenv("USERPROFILE", home)
		if err := os.WriteFile(filepath.Join(home, ".bashrc"), []byte("# unrelated rc\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		r := checkBashLikeProfile(home)
		if r.Status != "warn" {
			t.Errorf("status = %q, want warn (not sourced)", r.Status)
		}
		if !strings.Contains(r.Detail, "onix --init") {
			t.Errorf("detail = %q, want it to suggest 'onix --init'", r.Detail)
		}
	})

	t.Run("ok when rc sources the snippet", func(t *testing.T) {
		home := t.TempDir()
		t.Setenv("HOME", home)
		t.Setenv("USERPROFILE", home)
		// .zshrc references the absolute path that snippet.BashPath would return.
		body := "# onix\n. '" + snippet.BashPath(home) + "'\n"
		if err := os.WriteFile(filepath.Join(home, ".zshrc"), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
		r := checkBashLikeProfile(home)
		if r.Status != "ok" {
			t.Errorf("status = %q (detail=%s), want ok", r.Status, r.Detail)
		}
	})
}

func TestShortSHA(t *testing.T) {
	tests := []struct {
		in, want string
	}{
		{"", ""},
		{"abc", "abc"},
		{"123456789012", "123456789012"},  // exactly 12, untouched
		{"1234567890123", "123456789012"}, // 13 → 12
		{"abcdef0123456789deadbeef", "abcdef012345"},
	}
	for _, tc := range tests {
		if got := shortSHA(tc.in); got != tc.want {
			t.Errorf("shortSHA(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestExtractBashSnippetPin(t *testing.T) {
	t.Run("happy path", func(t *testing.T) {
		dir := t.TempDir()
		if err := os.MkdirAll(filepath.Join(dir, "shell"), 0o755); err != nil {
			t.Fatal(err)
		}
		body := "# header\nexport ONIX_EXE='/usr/local/bin/onix'\nfoo() { :; }\n"
		if err := os.WriteFile(snippet.BashPath(dir), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
		if got := extractBashSnippetPin(dir); got != "/usr/local/bin/onix" {
			t.Errorf("got %q, want /usr/local/bin/onix", got)
		}
	})

	t.Run("missing file", func(t *testing.T) {
		dir := t.TempDir()
		if got := extractBashSnippetPin(dir); got != "" {
			t.Errorf("got %q, want empty for missing file", got)
		}
	})

	t.Run("missing pin line", func(t *testing.T) {
		dir := t.TempDir()
		if err := os.MkdirAll(filepath.Join(dir, "shell"), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(snippet.BashPath(dir), []byte("# no pin here\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		if got := extractBashSnippetPin(dir); got != "" {
			t.Errorf("got %q, want empty when no pin line present", got)
		}
	})
}

func TestDoctorCmd(t *testing.T) {
	home := t.TempDir()
	// Initialize the home so doctor has something to check
	if err := (&InitCmd{SkipProfile: true}).Run(context.Background(), &env{Home: home, Stdout: os.Stdout, Stderr: os.Stderr, Stdin: os.Stdin}); err != nil {
		t.Fatal(err)
	}

	// Run doctor
	if err := (&DoctorCmd{}).Run(context.Background(), &env{Home: home, Stdout: os.Stdout, Stderr: os.Stderr, Stdin: os.Stdin}); err != nil {
		t.Errorf("DoctorCmd.Run: %v", err)
	}

	// Run doctor in JSON mode
	if err := (&DoctorCmd{}).Run(context.Background(), &env{Home: home, Stdout: os.Stdout, Stderr: os.Stderr, Stdin: os.Stdin, JSON: true}); err != nil {
		t.Errorf("DoctorCmd.Run (JSON): %v", err)
	}
}

func TestCheckPluginsFile(t *testing.T) {
	home := t.TempDir()

	t.Run("missing", func(t *testing.T) {
		r := checkPluginsFile(home)
		if r.Status != "ok" || !strings.Contains(r.Detail, "absent") {
			t.Errorf("got %+v, want ok/absent", r)
		}
	})

	t.Run("empty", func(t *testing.T) {
		if err := os.WriteFile(filepath.Join(home, "plugins.toml"), []byte("plugins = []\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		r := checkPluginsFile(home)
		if r.Status != "ok" || !strings.Contains(r.Detail, "no plugins") {
			t.Errorf("got %+v, want ok/no plugins", r)
		}
	})

	t.Run("malformed", func(t *testing.T) {
		if err := os.WriteFile(filepath.Join(home, "plugins.toml"), []byte("this is not toml\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		r := checkPluginsFile(home)
		if r.Status != "err" {
			t.Errorf("got status %q, want err", r.Status)
		}
	})
}

func TestCheckSegmentsFile(t *testing.T) {
	home := t.TempDir()

	t.Run("missing", func(t *testing.T) {
		r := checkSegmentsFile(home)
		if r.Status != "ok" || !strings.Contains(r.Detail, "absent") {
			t.Errorf("got %+v, want ok/absent", r)
		}
	})

	t.Run("empty", func(t *testing.T) {
		if err := os.WriteFile(filepath.Join(home, "segments.toml"), []byte("contexts = []\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		r := checkSegmentsFile(home)
		if r.Status != "ok" || !strings.Contains(r.Detail, "no contexts") {
			t.Errorf("got %+v, want ok/no contexts", r)
		}
	})
}

func TestCheckInstalledPlugins(t *testing.T) {
	home := t.TempDir()

	t.Run("no plugins", func(t *testing.T) {
		results := checkInstalledPlugins(home)
		if len(results) != 0 {
			t.Errorf("got %d results, want 0", len(results))
		}
	})

	t.Run("missing binary", func(t *testing.T) {
		pf := &plugins.PluginsFile{
			Plugins: []plugins.Plugin{
				{Name: "tts", Repo: "user/repo", SHA: "abc"},
			},
		}
		if err := plugins.SavePlugins(home, pf); err != nil {
			t.Fatal(err)
		}
		results := checkInstalledPlugins(home)
		if len(results) != 1 || results[0].Status != "err" {
			t.Errorf("got %+v, want 1 err result", results)
		}
	})

	t.Run("unpinned warning", func(t *testing.T) {
		repo := "user/repo"
		pf := &plugins.PluginsFile{
			Plugins: []plugins.Plugin{
				{Name: "tts", Repo: repo, Unpinned: true},
			},
		}
		if err := plugins.SavePlugins(home, pf); err != nil {
			t.Fatal(err)
		}
		// Stub the binary
		binPath := plugins.BinaryPath(home, repo)
		if err := os.MkdirAll(filepath.Dir(binPath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(binPath, []byte("stub"), 0o755); err != nil {
			t.Fatal(err)
		}

		results := checkInstalledPlugins(home)
		if len(results) != 1 || results[0].Status != "warn" {
			t.Errorf("got %+v, want 1 warn result", results)
		}
	})
}
