[fzf.destination]
prompt = "Jump > "
layout = "reverse-list"
preview = "dir /b \"{}\" 2>nul"
preview_window = "right:35%,border-left"
header = "Enter choose  |  Esc cancel"
height = "50%"

[fzf.sg]
prompt = "sg > "
layout = "default"
color = "hl:-1:underline,hl+:-1:underline:reverse"
preview = "bat --style=numbers --color=always {1} --highlight-line {2}"
preview_window = "right:45%,border-left,+{2}/3"

[fzf.ff]
prompt = "ff > "
layout = "default"
preview = "bat --style=numbers --color=always --line-range=:160 {}"
preview_window = "right:42%,border-left"
