[fzf.destination]
prompt = "Destination > "
layout = "reverse-list"
preview = "dir /b \"{}\" 2>nul"
preview_window = "up,45%,border-bottom"
header = "Enter to confirm  |  Esc manual"
height = "60%"

[fzf.sg]
prompt = "sg > "
layout = "default"
color = "hl:-1:underline,hl+:-1:underline:reverse"
preview = "bat --style=numbers --color=always {1} --highlight-line {2}"
preview_window = "up,65%,border-bottom,+{2}+3/3,~3"

[fzf.ff]
prompt = "ff > "
layout = "default"
preview = "bat --style=numbers --color=always --line-range=:220 {}"
preview_window = "up,55%,border-bottom"
