name: Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        go: ['1.26']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v5.0.0

      - uses: actions/setup-go@4a3601113188429b0e3728a4481356a2179ad73c  # v6.4.0
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Vet
        run: go vet ./...

      - name: govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...

      - name: Test
        run: go test ./...
